### ISSUE TITLE
Link to https://go.uniwue.de/videoqoe is 404

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [lsinfo3/yomo-wrapperapp#5]
Link to https://go.uniwue.de/videoqoe is 404

Also a short update on the main site about the current status #4 would be nice. Thanks!

Edit:
Let me be more verbose. First of all, thanks for all your work on QoS video testing, which is really awesome.
I just saw that you have many more ongoing projects (yomo-docker, yomo-browser-plugin). It would be nice to have a overview of active and abandoned projects (and maybe put a link to this overview in each repository?).

**Comment by florianwa** [comment]
Link is updated now. However, since I changed to the Lucerne University of Applied Sciences and Arts this webpage is quite outdated. Same applies to the programs and tools regarding YouTube QoE Monitoring. 

You may find further information here:

"A Wrapper for Automatic Measurements with YouTube's Native Android App," 2018 Network Traffic Measurement and Analysis Conference (TMA), 2018, pp. 1-8, doi: 10.23919/TMA.2018.8506488.

https://www.bibsonomy.org/person/f.wamser.1
